### ISSUE TITLE
Spectrum images are not read with shape in correct order

### ISSUE THREAD

**Issue by thomasaarholt** [niermann/gms_plugin_hdf5#2]
This is probably a hyperspy-related thing, but spectrum images are not read in in the correct order. I've attached a file as an example. It should provide an image on screen with a pixel in each image. Instead, one of the image axes is correctly on the y-axis, but the x-axis is made up of the energy channels in the spectrum.

[test.zip](https://github.com/niermann/gms_plugin_hdf5/files/1108576/test.zip)

**Comment by niermann** [comment]
The HDF5 format can be used to store arbitrary kinds of datasets. The HDF5 format does not specify any interpretation of the datasets, like axis 0 is the x-axis, axis 2 is the energy axis, sampling along an axis, calibrations, etc. Such specification is up to the user, or is provided by further formats built upon the HDF5 format (like CDF, EMD, or the hyperspy format). 

The plugin provides functions for DM scripting to read such HDF5 files (however only a limited subset of the capabilities of the HDF5lib). It also provides functions to browse and read attributes associated with the datasets stored in the HDF5 file. Usually these attributes are used to store this kind of further specifications.

Within the release package, there is a DM script provided as example, which uses the plugin to read datasets from it, using some custom specs (X axis is axis #0, calibration of axes) of my own. In order to read hyperspy files you need to write your own DM script, which knows how to interpret hyperspy files. HDF5 files are only used as container for the to store the hyperspy datasets. The plugin only provides methods to read this container, not to read hyperspy datasets as DM datasets. 

I encourage anyone to write a DM script for reading of hyperspy files. I'm willing to help as best I can. However, it is unlikely that I will write such a script in the next future. I'm not very familiar with the hyperspy format (though, I suppose its specs are available), I'm not using it for my work, and mostly I'm not very fond of DM scripting at all (personally I enjoy python for this).
